# .github/labeler.yml

# Define label rules based on modified paths
label-rulesaaaa:
  - label: bug
    paths:
      - "src/**/*.js"
    - "label: js-bug"
      paths:
      - "tests/**/*.js"

  - label: feature
    paths:
      - "src/**/*.jsx"
    - "label: jsx-feature"
      paths:
      - "tests/**/*.jsx"

# Define default labels to be applied if no rules match
default-labels:
  - "needs-review"

# Define labels to be removed if no rules match
remove-labels:
  - "in-progress"
