name: Pull Request Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Label PR based on labeler.yml
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml